= Documenting VG Soft Primer

== Introduction
This project shows best practices for developing software project with Spring Boot as backend technology and ELM for frontend.

== Testing

Integration tests are configured as described in https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests

If integration test directory is marked es source and not test (blue icon and not green) you should manualy change it in Intellij project properties, but after gradle refresh it should stay marked as test.

== Upgrading gradlew version

Described https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

Eg.

[source,bash]
----
$ ./gradlew wrapper --gradle-version 5.6.2
----

== Code coverage

Check task only depends on `jacocoTestCoverageVerification`. This is to speed up build. Reports are created only when explicitly asked.

Developer will be interested in jacoco reports only when build is failing because if low coverage or when he is interested in code coverage.

Reports can be created by running :

[source,bash]
----
$ ./gradlew clean jacocoIntegrationTestReport jacocoTestReport jacocoUnitTestReport
----

== Checkstyle
We have taken checkstyle configuration from https://github.com/checkstyle/checkstyle/raw/master/src/main/resources/google_checks.xml

== SpotBugs
We were not able to move spotbug to separate configuration.

== Pro Tip
First configure plugin in build.gradle.kts and then look for types that will IntelliJ show and then muve them to separate file.


== Default database (H2)

By default embedded H2 database is started and can be accessed at URL http://localhost:8080/h2-console/

JDBC URL: jdbc:h2:mem:testdb