= Documenting VG Soft Primer

== Introduction
This project shows best practices for developing software project with Spring Boot as backend technology and ELM for frontend.

== Testing

Integration tests are configured as described in https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests

If integration test directory is marked es source and not test (blue icon and not green) you should manually change it in Intellij project properties, but after gradle refresh it should stay marked as test.

== Upgrading gradlew version

Described https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

Eg.

[source,bash]
----
$ ./gradlew wrapper --gradle-version 5.6.2
----

== Code coverage

Check task only depends on `jacocoTestCoverageVerification`. This is to speed up build. Reports are created only when explicitly asked.

Developer will be interested in jacoco reports only when build is failing because if low coverage or when he is interested in code coverage.

Reports can be created by running :

[source,bash]
----
$ ./gradlew clean jacocoIntegrationTestReport jacocoTestReport jacocoUnitTestReport
----

== Checkstyle
We have taken checkstyle configuration from https://github.com/checkstyle/checkstyle/raw/master/src/main/resources/google_checks.xml

== SpotBugs
We were not able to move spotbug to separate configuration.

== Pro Tip
First configure plugin in build.gradle.kts and then look for types that will IntelliJ show and then muve them to separate file.


== Default database (H2)

By default embedded H2 database is started and can be accessed at URL https://localhost:8443/h2-console/

JDBC URL: jdbc:h2:mem:testdb

== Running application

First you need to build application with:
[source,bash]
----
./gradlew clean build
----
Then you can start application with:
[source,bash]
----
java -jar ./backend/build/libs/backend.jar
----

== Debugging build
[source,bash]
----
./gradlew -Dorg.gradle.debug=true -Penv=dev clean build
----


=== Profiles

There are two profiles. DEFAULT profile is default profile that is using H2 database and DEV profile that is using
PostgreSQL database.

DEV profile is using flyway to version database and for DEFAULT profile database is created by hibernate.

==== Default profile

This profile is used for quick user testing of application. Application class with main method is started without any
profiles. H2 database is used and tables are automatically created when application starts. Test data is inserted at
start of application with Application Listener that listens for ContextRefreshedEvent. Developer can start application
in debug mode and put brake points in code. Database can be access over H2 console that is started whit application.

Building package:
[source,bash]
----
./gradlew build
----

Running application:
[source,bash]
----
java -jar ./backend/build/libs/backend.jar
----

==== Test profile

This profile is for running automated tests (unit,integration, etc.) Dhis profile also uses H2 database but test data is
inserted in setup method of test and not by ApplicationListener.

==== Staging profile

This profile is used to simulate production environment. Same database is used in dev and prod profile (PostgresSQL).
database schema is initialized by flyway scripts and initial data can be inserted also by flyway scripts or with
ApplicationListener. Developer can run application in debug mode and debug code and can connect to database with any
db client and inspect results.

Building package:
[source,bash]
----
./gradlew build
----

Starting Postgres database docker:
[source,bash]
----
docker run -it --rm --name vg-postgres -p 5432:5432 -e POSTGRES_USER=rootuser -e POSTGRES_PASSWORD=rootpassword -e POSTGRES_DB=vgsoft postgres
----

Application can be run with staging profile from ide or from terminal with:
[source,bash]
----
java -Dspring.profiles.active=staging -jar ./backend/build/libs/backend.jar
----

==== Prod profile

This profile is for running application in prtoduction. Schema is initialazed with flyway scripts.

Application can be run with prod profile from ide or from terminal with:
[source,bash]
----
java -Dspring.profiles.active=prod -jar ./backend/build/libs/backend.jar
----